apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-node-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-node-project
  template:
    metadata:
      labels:
        app: fullstack-node-project
    spec:
      containers:
        - name: fullstack-node-project
          image: nandanisah/fullstack-node-project  # Ensure this matches the built image tag
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-node-project
spec:
  type: ClusterIP  # This exposes the service internally in the cluster
  selector:
    app: fullstack-node-project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000