version: '3'
services:
  fullstack-node-project:
    build:
      context: .
      dockerfile: Dockerfile-multi-stage   # Specify the Dockerfile you want to use
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
