apiVersion: app/v1
kind: Deployment
metadata:
  name: fullstack-node-project
spec:
  replicas: 1
  selector:
    matchlabels:
      app: fullstack-node-project
  template:
    metadat:
      labels:
        app: fullstack-node-project
    spec:
      containers:
        - name: fullstack-node-project
          image: fullstack-node-project:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"


---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-node-project
spec:
  type: NodePort
  selector:
    app: fullstack-node-project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000